### ISSUE TITLE
Feedback Score

### ISSUE THREAD

**Issue by tjoye20** [Ghar1b/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4 - Exceeds Expectations
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4 - Exceeds Expectations
 
### Overall Score: 16/16
Good job on this, Ibrahim. It's clear you have a good understanding of HTML and CSS basics. Looking forward to your next project, keep it up!

**Comment by Ghar1b** [comment]
Thank you for a swift review!
